# Generated by Django 3.2.15 on 2024-06-26 13:11

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academic', '0009_auto_20240626_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='attachments',
            field=models.FileField(blank=True, default=datetime.datetime(2024, 6, 26, 13, 11, 33, 912213), upload_to='attachments/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='enrolled_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
