# Generated by Django 3.2.15 on 2024-06-26 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0010_auto_20240626_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentassignment',
            name='marks_awarded',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='studentassignment',
            name='plagiarism_percentage',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
