# Generated by Django 3.2.15 on 2024-06-26 16:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0012_auto_20240626_1357'),
    ]

    operations = [
        migrations.AddField(
    model_name='submission',
    name='course',
    field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academic.course'),
),
    ]
