# Generated by Django 3.2.15 on 2024-06-26 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0013_submission_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='academic.course'),
        ),
    ]
