# Generated by Django 4.2.16 on 2026-09-23 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academic', '0014_alter_submission_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('register', 'Registration'), ('submit', 'Assignment submitted'), ('extract', 'Text extracted'), ('detect', 'Detection run'), ('report_view', 'Report viewed'), ('course_create', 'Course created'), ('course_delete', 'Course deleted'), ('assignment_create', 'Assignment created'), ('assignment_delete', 'Assignment deleted'), ('enroll', 'Student enrolled'), ('error', 'Error')], max_length=32)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('method', models.CharField(default='combined', max_length=32)),
                ('method_scores', models.JSONField(blank=True, default=dict)),
                ('matched_passages', models.JSONField(blank=True, default=list)),
                ('paraphrase_matches', models.JSONField(blank=True, default=list)),
                ('structural_score', models.FloatField(default=0.0)),
                ('semantic_score', models.FloatField(default=0.0)),
                ('is_exact_duplicate', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'matches',
                'ordering': ['-score'],
            },
        ),
        migrations.CreateModel(
            name='PlagiarismReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(default='combined', max_length=32)),
                ('threshold', models.FloatField(default=40.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('submissions_analyzed', models.IntegerField(default=0)),
                ('pairs_compared', models.IntegerField(default=0)),
                ('flagged_count', models.IntegerField(default=0)),
                ('duration_seconds', models.FloatField(default=0.0)),
                ('semantic_backend', models.CharField(blank=True, default='', max_length=40)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_index', models.FloatField(default=0.0)),
                ('highest_match_score', models.FloatField(default=0.0)),
                ('flagged', models.BooleanField(default=False)),
                ('is_exact_duplicate', models.BooleanField(default=False)),
                ('marks_awarded', models.FloatField(default=0.0)),
                ('marks_deducted', models.FloatField(default=0.0)),
                ('severity', models.CharField(default='none', max_length=16)),
                ('summary', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-similarity_index'],
            },
        ),
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['-due_date']},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['course_code']},
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['-submission_date']},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['user__username']},
        ),
        migrations.AddField(
            model_name='submission',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='submission',
            name='extracted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='extracted_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='submission',
            name='extraction_format',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='submission',
            name='extraction_warnings',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='submission',
            name='word_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(fields=('assignment', 'student'), name='unique_submission_per_student'),
        ),
        migrations.AddField(
            model_name='submissionresult',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='academic.plagiarismreport'),
        ),
        migrations.AddField(
            model_name='submissionresult',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='academic.submission'),
        ),
        migrations.AddField(
            model_name='plagiarismreport',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='academic.assignment'),
        ),
        migrations.AddField(
            model_name='plagiarismreport',
            name='generated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='match',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='academic.plagiarismreport'),
        ),
        migrations.AddField(
            model_name='match',
            name='submission_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_a', to='academic.submission'),
        ),
        migrations.AddField(
            model_name='match',
            name='submission_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_b', to='academic.submission'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='submissionresult',
            constraint=models.UniqueConstraint(fields=('report', 'submission'), name='unique_result_per_report'),
        ),
    ]
