# Generated by Django 4.2.16 on 2026-09-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0015_activitylog_match_plagiarismreport_submissionresult_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plagiarismreport',
            name='archive_matches_found',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submissionresult',
            name='archive_matches',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='submissionresult',
            name='matched_archive',
            field=models.BooleanField(default=False),
        ),
    ]
